package com.danym.stockinvestingapp.model
import com.fasterxml.jackson.annotation.JsonProperty

data class StockInfo(
    @JsonProperty("symbol") val symbol: String,
    @JsonProperty("price") val price: Double,
    @JsonProperty("beta") val beta: Double,
    @JsonProperty("volAvg") val volAvg: Int,
    @JsonProperty("mktCap") val mktCap: Long,
    @JsonProperty("lastDiv") val lastDiv: Double,
    @JsonProperty("range") val range: String,
    @JsonProperty("changes") val changes: Double,
    @JsonProperty("companyName") val companyName: String,
    @JsonProperty("currency") val currency: String,
    @JsonProperty("cik") val cik: String,
    @JsonProperty("isin") val isin: String,
    @JsonProperty("cusip") val cusip: String,
    @JsonProperty("exchange") val exchange: String,
    @JsonProperty("exchangeShortName") val exchangeShortName: String,
    @JsonProperty("industry") val industry: String,
    @JsonProperty("website") val website: String,
    @JsonProperty("description") val description: String,
    @JsonProperty("ceo") val ceo: String,
    @JsonProperty("sector") val sector: String,
    @JsonProperty("country") val country: String,
    @JsonProperty("fullTimeEmployees") val fullTimeEmployees: String,
    @JsonProperty("phone") val phone: String,
    @JsonProperty("address") val address: String,
    @JsonProperty("city") val city: String,
    @JsonProperty("state") val state: String,
    @JsonProperty("zip") val zip: String,
    @JsonProperty("dcfDiff") val dcfDiff: Double,
    @JsonProperty("dcf") val dcf: Double,
    @JsonProperty("image") val image: String,
    @JsonProperty("ipoDate") val ipoDate: String,
    @JsonProperty("defaultImage") val defaultImage: Boolean,
    @JsonProperty("isEtf") val isEtf: Boolean,
    @JsonProperty("isActivelyTrading") val isActivelyTrading: Boolean,
    @JsonProperty("isAdr") val isAdr: Boolean,
    @JsonProperty("isFund") val isFund: Boolean
)
